name: 'Danger JS'
on: [pull_request]

jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install yarn
        run: npm install -g yarn
      - uses: actions/cache@v4
        id: node-module-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: yarn install
        run: yarn install  --frozen-lockfile
      - name: Danger
        run: BRANCH=${GITHUB_REF##*/} yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
